version: '3.8'

services:
  user-api-gw:
    build: .
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
    networks:
      - microservices

  eureka:
    image: steeltoeoss/eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge